/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simplevm.app;

import simplevm.vm.VirtualMachine;

public class App {
    public static void main(String[] args) {
        System.out.println("SimpleVM Interpreter v0.0");

        VirtualMachine vm = new VirtualMachine();
    }
}
